import 'dotenv/config'
import readline from 'readline/promises'
import { ChatGoogleGenerativeAI } from "@langchain/google-genai";
import { ChatMistralAI } from '@langchain/mistralai'
import { HumanMessage, tool, SystemMessage, createAgent, AIMessage } from "langchain"
import sendEmail from './mail.service.js';
import internetSearch from './internet.service.js';
import * as z from "zod"



const geminiModel = new ChatGoogleGenerativeAI({
    model: "gemini-2.5-flash-lite",
    apiKey: process.env.GEMINI_API_KEY
})

const emailTool = tool(   // created a tool that can be used by LLM via langchain
    sendEmail,
    {
        name: "send_email",
        description: "use this tool when user ask to send email",
        schema: z.object({
            to: z.string().describe("reciever email address"),
            subject: z.string().describe("subject of email"),
            html: z.string().describe("structure of email")
        })
    }
)
const internetTool = tool(
    internetSearch,
    {
        name: "internet_results",
        description: " Use this tool to search the internet for real-time, up-to-date, or missing information that cannot be reliably answered from existing knowledge. It should be used when the user’s query involves recent events, live data, trends, or specific entities such as people, companies, products, or places, or when fact-checking and verification are required. The tool is also appropriate when the query is unclear and additional context is needed from external sources. Avoid using this tool for general knowledge questions, creative tasks, coding, or explanations that do not require external data. Always provide a clear, concise, and relevant search query when invoking the tool, and return only the most useful and accurate information.After receiving tool results, always generate a clear and helpful final answer for the user.Do not return empty content",
        schema: z.string().describe("provide the prompt")
    }
)

const mistralModel = new ChatMistralAI({
    model: "mistral-small-latest",
    apiKey: process.env.MISTRAL_API_KEY
})
const agent = createAgent({
    model: geminiModel,
    tools: [emailTool, internetTool]
})



async function generateResponse(prompt, history) {
    let response
    if (prompt) {
        response = await agent.invoke({ messages: new HumanMessage(prompt) })

    }
    else if (history) {
        response = await agent.invoke({
            messages: history.map((prev) => {
                return prev.role === "user" ? new HumanMessage(prev.content) : new AIMessage(prev.content)
            })
        })
    }
    console.log(response)
    if(response.tool_calls && response.tool_calls.length > 0){
        const toolResult = response.ToolMessage
        console.log(toolResult)
    }
    // console.log("ai response in service",response)
    return response.messages[response.messages.length - 1].content
}

async function generateTitle(prompt) {
    const response = await mistralModel.invoke([new SystemMessage("you are specialiazed ai model that accepts the prompt and generate the very concise and accurate title for the input you recieved the title generated by you usually consist 2-4 words dont provide multiple output provide only single concise output of 2-4 words"), new HumanMessage(prompt)])

    return response.content

}
export default { generateResponse, generateTitle }